-- This file contains a text translation for various flags and tokens in the 
-- game that don't have a simple translation, or benefit from some additional
-- information. 

-- Flags
creatureFlags = {
-- BIOMES 
  ANY_LAND                              = 'Any Land',
  ALL_MAIN                              = 'All Main',
  ANY_OCEAN                             = 'Any Ocean',
  ANY_LAKE                              = 'Any Lake',
  ANY_TEMPERATE_LAKE                    = 'Temperate Lakes',
  ANY_TROPICAL_LAKE                     = 'Tropical Lakes',
  ANY_RIVER                             = 'Lives in any rivers',
  ANY_TEMPERATE_RIVER                   = 'Temperate Rivers',
  ANY_TROPICAL_RIVER                    = 'Tropical Rivers',
  ANY_POOL                              = 'Any Pool',
  NOT_FREEZING                          = 'Not Freezing',
  ANY_TEMPERATE                         = 'Any Temperate',
  ANY_TROPICAL                          = 'Any Tropical',
  ANY_FOREST                            = 'Any Forest',
  ANY_SHRUBLAND                         = 'Any Shrubland',
  ANY_GRASSLAND                         = 'Any Grassland',
  ANY_SAVANNA                           = 'Any Savanna',
  ANY_TEMPERATE_FOREST                  = 'Any Temperate Forest',
  ANY_TROPICAL_FOREST                   = 'Any Tropical Forest',
  ANY_TEMPERATE_BROADLEAF               = 'Any Temperate Vegetation',
  ANY_TROPICAL_BROADLEAF                = 'Any Tropical Vegetation',
  ANY_WETLAND                           = 'Any Wetland',
  ANY_TEMPERATE_WETLAND                 = 'Any Temperate Wetland',
  ANY_TROPICAL_WETLAND                  = 'Any Tropical Wetland',
  ANY_TEMPERATE_MARSH                   = 'Any Temperate Marsh',
  ANY_TROPICAL_MARSH                    = 'Any Tropical Marsh',
  ANY_TEMPERATE_SWAMP                   = 'Any Temperate Swamp',
  ANY_TROPICAL_SWAMP                    = 'Any Tropical Swamp',
  ANY_DESERT                            = 'Any Desert',
  MOUNTAIN                              = 'Mountains',
  MOUNTAINS                             = 'Mountains',
  GLACIER                               = 'Glaciers',
  TUNDRA                                = 'Tundra',
  SWAMP_TEMPERATE_FRESHWATER            = 'Temperate Freshwater Swamp',
  SWAMP_TEMPERATE_SALTWATER             = 'Temperate Saltwater Swamp',
  SWAMP_TROPICAL_FRESHWATER             = 'Tropical Freshwater Swamp',
  SWAMP_TROPICAL_SALTWATER              = 'Tropical Saltwater Swamp',
  SWAMP_MANGROVE                        = 'Mangrove Swamp',
  MARSH_TEMPERATE_FRESHWATER            = 'Temperate Freshwater Marsh',
  MARSH_TEMPERATE_SALTWATER             = 'Temperate Saltwater Marsh',
  MARSH_TROPICAL_FRESHWATER             = 'Tropical Freshwater Marsh',
  MARSH_TROPICAL_SALTWATER              = 'Tropical Saltwater Marsh',
  FOREST_TAIGA                          = 'Taiga',
  TAIGA                                 = 'Taiga',
  FOREST_TEMPERATE_BROADLEAF            = 'Temperate Broadleaf Forest',
  FOREST_TEMPERATE_CONIFER              = 'Temperate Conifer Forest',
  FOREST_TROPICAL_DRY_BROADLEAF         = 'Tropical Dry Broadleaf Forest',
  FOREST_TROPICAL_MOIST_BROADLEAF       = 'Tropical Moist Broadleaf Forest',
  FOREST_TROPICAL_CONIFER               = 'Tropical Conifer Forest',
  GRASSLAND_TEMPERATE                   = 'Temperate Grassland',
  GRASSLAND_TROPICAL                    = 'Tropical Grassland',
  SHRUBLAND_TEMPERATE                   = 'Temperate Shrubland',
  SHRUBLAND_TROPICAL                    = 'Tropical Shrubland',
  SAVANNA_TEMPERATE                     = 'Temperate Savanna',
  SAVANNA_TROPICAL                      = 'Tropical Savanna',
  OCEAN_ARCTIC                          = 'Arctic Ocean',
  OCEAN_TEMPERATE                       = 'Temperate Ocean',
  OCEAN_TROPICAL                        = 'Tropical Ocean',
  DESERT_BADLAND                        = 'Badlands',
  DESERT_ROCK                           = 'Rocky Wastes',
  DESERT_SAND                           = 'Sandy Desert',
  POOL_TEMPERATE_FRESHWATER             = 'Temperate Freshwater Pool',
  POOL_TEMPERATE_BRACKISHWATER          = 'Temperate Brackishwater Pool',
  POOL_TEMPERATE_SALTWATER              = 'Temperate Saltwater Pool',
  POOL_TROPICAL_FRESHWATER              = 'Tropical Freshwater Pool',
  POOL_TROPICAL_BRACKISHWATER           = 'Tropical Brackishwater Pool',
  POOL_TROPICAL_SALTWATER               = 'Tropical Saltwater Pool',
  LAKE_TEMPERATE_FRESHWATER             = 'Temperate Freshwater Lake',
  LAKE_TEMPERATE_BRACKISHWATER          = 'Temperate Brackishwater Lake',
  LAKE_TEMPERATE_SALTWATER              = 'Temperate Saltwater Lake',
  LAKE_TROPICAL_FRESHWATER              = 'Tropical Freshwater Lake',
  LAKE_TROPICAL_BRACKISHWATER           = 'Tropical Brackishwater Lake',
  LAKE_TROPICAL_SALTWATER               = 'Tropical Saltwater Lake',
  RIVER_TEMPERATE_FRESHWATER            = 'Temperate Freshwater River',
  RIVER_TEMPERATE_BRACKISHWATER         = 'Temperate Brackishwater River',
  RIVER_TEMPERATE_SALTWATER             = 'Temperate Saltwater River',
  RIVER_TROPICAL_FRESHWATER             = 'Tropical Freshwater River',
  RIVER_TROPICAL_BRACKISHWATER          = 'Tropical Brackishwater River',
  RIVER_TROPICAL_SALTWATER              = 'Tropical Saltwater River',
  SUBTERRANEAN_WATER                    = 'Subterranean Water',
  SUBTERRANEAN_CHASM                    = 'Subterranean Chasm',
  SUBTERRANEAN_LAVA                     = 'Subterranean Lava',
  BIOME_MOUNTAIN                        = 'Mountain',
  BIOME_GLACIER                         = 'Glacier',
  BIOME_TUNDRA                          = 'Tundra',
  BIOME_SWAMP_TEMPERATE_FRESHWATER      = 'Temperate Freshwater Swamp',
  BIOME_SWAMP_TEMPERATE_SALTWATER       = 'Temperate Saltwater Swamp',
  BIOME_MARSH_TEMPERATE_FRESHWATER      = 'Temperate Freshwater Marsh',
  BIOME_MARSH_TEMPERATE_SALTWATER       = 'Temperate Saltwater Marsh',
  BIOME_SWAMP_TROPICAL_FRESHWATER       = 'Tropical Freshwater Swamp',
  BIOME_SWAMP_TROPICAL_SALTWATER        = 'Tropical Saltwater Swamp',
  BIOME_SWAMP_MANGROVE                  = 'Mangrove Swamp',
  BIOME_MARSH_TROPICAL_FRESHWATER       = 'Tropical Freshwater Marsh',
  BIOME_MARSH_TROPICAL_SALTWATER        = 'Tropical Saltwater Marsh',
  BIOME_FOREST_TAIGA                    = 'Taiga',
  BIOME_FOREST_TEMPERATE_CONIFER        = 'Temperate Coniferous Forest',
  BIOME_FOREST_TEMPERATE_BROADLEAF      = 'Temperate Broadlead Forest',
  BIOME_FOREST_TROPICAL_CONIFER         = 'Tropical Coniferous Forest',
  BIOME_FOREST_TROPICAL_DRY_BROADLEAF   = 'Tropical Dry Broadleaf Forest',
  BIOME_FOREST_TROPICAL_MOIST_BROADLEAF = 'Tropical Moist Broadleaf Forest',
  BIOME_GRASSLAND_TEMPERATE             = 'Temperate Grassland',
  BIOME_SAVANNA_TEMPERATE               = 'Temperate Savanna',
  BIOME_SHRUBLAND_TEMPERATE             = 'Temperate Shrubland',
  BIOME_GRASSLAND_TROPICAL              = 'Tropical Grassland',
  BIOME_SAVANNA_TROPICAL                = 'Tropical Savanna',
  BIOME_SHRUBLAND_TROPICAL              = 'Tropical Shrubland',
  BIOME_DESERT_BADLAND                  = 'Badland Desert',
  BIOME_DESERT_ROCK                     = 'Rock Desert',
  BIOME_DESERT_SAND                     = 'Sand Desert',
  BIOME_OCEAN_TROPICAL                  = 'Tropical Ocean',
  BIOME_OCEAN_TEMPERATE                 = 'Temperate Ocean',
  BIOME_OCEAN_ARCTIC                    = 'Arctic Ocean',
  BIOME_SUBTERRANEAN_WATER              = 'Underground Water',
  BIOME_SUBTERRANEAN_CHASM              = 'Ungerground Chasm',
  BIOME_SUBTERRANEAN_LAVA               = 'Underground Lava',
  BIOME_POOL_TEMPERATE_FRESHWATER       = 'Temperate Freshwater Pool',
  BIOME_POOL_TEMPERATE_BRACKISHWATER    = 'Temperate Brackishwater Pool',
  BIOME_POOL_TEMPERATE_SALTWATER        = 'Temperate Saltwater Pool',
  BIOME_POOL_TROPICAL_FRESHWATER        = 'Tropical Freshwater Pool',
  BIOME_POOL_TROPICAL_BRACKISHWATER     = 'Tropical Brackishwater Pool',
  BIOME_POOL_TROPICAL_SALTWATER         = 'Tropical Saltwater Pool',
  BIOME_LAKE_TEMPERATE_FRESHWATER       = 'Temperate Freshwater Lake',
  BIOME_LAKE_TEMPERATE_BRACKISHWATER    = 'Temperate Brackishwater Lake',
  BIOME_LAKE_TEMPERATE_SALTWATER        = 'Temperate Saltwater Lake',
  BIOME_LAKE_TROPICAL_FRESHWATER        = 'Tropical Freshwater Lake',
  BIOME_LAKE_TROPICAL_BRACKISHWATER     = 'Tropical Brackishwater Lake',
  BIOME_LAKE_TROPICAL_SALTWATER         = 'Tropical Saltwater Lake',
  BIOME_RIVER_TEMPERATE_FRESHWATER      = 'Temperate Freshwater River',
  BIOME_RIVER_TEMPERATE_BRACKISHWATER   = 'Temperate Brackishwater River',
  BIOME_RIVER_TEMPERATE_SALTWATER       = 'Temperate Saltwater River',
  BIOME_RIVER_TROPICAL_FRESHWATER       = 'Tropical Freshwater River',
  BIOME_RIVER_TROPICAL_BRACKISHWATER    = 'Tropical Brackishwater River',
  BIOME_RIVER_TROPICAL_SALTWATER        = 'Tropical Saltwater River',

-- Habitats
  AMPHIBIOUS = 'Amphibious',
  AQUATIC    = 'Aquatic',
  GOOD       = 'Living in good biomes',
  EVIL       = 'Living in evil biomes',
  SAVAGE     = 'Living in savage biomes',

-- Activity
  ALL_ACTIVE  = 'At all times',
  DIURNAL     = 'During the day',
  NOCTURNAL   = 'During the night',
  CREPUSCULAR = 'At dawn and dusk',
  VESPERTINE  = 'At dusk',
  MATUTINAL   = 'At dawn'
  NO_SPRING   = 'Absent during the spring',
  NO_SUMMER   = 'Absent during the summer',
  NO_AUTUMN   = 'Absent during the fall',
  NO_WINTER   = 'Absent during the winter',

-- Utility
  COMMON_DOMESTIC   = 'Domesticated',
  WAGON_PULLER      = 'Can pull wagons',
  PACK_ANIMAL       = 'Can haul goods',
  TRAINABLE_HUNTING = 'Can be trained to hunt',
  TRAINABLE_WAR     = 'Can be trained for fighting',
  PET               = 'Can be tamed',
  PET_EXOTIC        = 'Can be tamed with difficulty',
  MOUNT             = 'Can be used as a mount',
  MOUNT_EXOTIC      = 'Can be used as a mount',
 
-- Diet             
  NO_EAT        = 'Does not need food',
  NO_DRINK      = 'Does not need drink',
  BONECARN      = 'Eats meat and bones',
  CARNIVORE     = 'Only eats meat',
  GRAZER        = 'Eats grass',
  GOBBLE_VERMIN = 'Eats vermin',

-- Behavior
  MISCHIEVOUS                 = 'Mischievous',
  CURIOUSBEAST_ANY            = 'Steals anything',
  CURIOUSBEAST_ITEM           = 'Steals items',
  CURIOUSBEAST_GUZZLER        = 'Steals drinks',
  CURIOUSBEAST_EATER          = 'Steals food',
  TRAPAVOID                   = 'Avoids traps',
  CAVE_ADAPT                  = 'Dislikes leaving caves',
  HUNTS_VERMIN                = 'Hunts vermin',
  SOUND_ALERT                 = 'Creates sounds when alerted',
  SOUND_PEACEFUL_INTERMITTENT = 'Creates sounds intermittently',
  CRAZED                      = 'Constantly berserk',
  FLEEQUICK                   = 'Quick to flee',
  AT_PEACE_WITH_WILDLIFE      = 'At peace with wildlife',
  AMBUSHPREDATOR              = 'Ambushes prey',
  OPPOSED_TO_LIFE             = 'Hostile to the living',

-- Movement
  FLIER          = 'Can fly',
  IMMOBILE       = 'Can not move',
  IMMOBILE_LAND  = 'Can not move on land',
  MEANDERER      = 'Meanders around',
  SWIMS_INNATE   = 'Can swim',
  CANNOT_JUMP    = 'Can not jump',
  STANCE_CLIMBER = 'can climb with its feet',
  CANNOT_CLIMB   = 'Can not climb',
  SWIMS_LEARNED  = 'Can learn to swim',
  VERMIN_MICRO   = 'Moves in a swarm',
  UNDERSWIM      = 'Swims underwater',

-- Immunities
  NO_DIZZINESS     = 'Does not get dizzy',
  NO_FEVERS        = 'Does not get fevers',
  NOEXERT          = 'Does not get tired',
  NOPAIN           = 'Does not feel pain',
  NOBREATHE        = 'Does not breath',
  NOSTUN           = 'Can not be stunned',
  PARALYZEIMMUNE   = 'Can not be paralyzed',
  NONAUSEA         = 'Does not get nauseous',
  NOEMOTION        = 'Does not feel emotion',
  NOFEAR           = 'Can not be scared',
  NO_SLEEP         = 'Does not need sleep',
  FIREIMMUNE       = 'Immune to fire',
  FIREIMMUNE_SUPER = 'Immune to dragonfire',
  WEBIMMUNE        = 'Does not get caught in webs',

-- Bonuses
  WEBBER                = 'Creates webs',
  THICKWEB              = 'Webs large targets',
  MAGMA_VISION          = 'Can see in lava',
  IMMOLATE              = 'Radiates fire',
  MULTIPART_FULL_VISION = 'Can see all around itself',
  CAN_SPEAK             = 'Can speak',
  CAN_LEARN             = 'Can learn',
  CANOPENDOORS          = 'Can open doors',
  LOCKPICKER            = 'Can pick locks',
  EQUIPS                = 'Can wear items',
  LISP                  = 'Speaks with a lisp',
  LIGHT_GEN             = 'Generates light',
  EXTRAVISION           = 'Can see in the dark',
  SLOW_LEARNER          = 'Slow learner',
  UTTERANCES            = 'Unintelligible utterances',

-- Body Flags
  NOT_BUTCHERABLE                = 'Can not be butchered',
  COOKABLE_LIVE                  = 'Can be cooked live',
  NOSKULL                        = 'Does not have a skull',
  NOSKIN                         = 'Does not have skin',
  NOBONES                        = 'Does not have bones',
  NOMEAT                         = 'Does not have meat',
  NOTHOUGHT                      = 'Does not have a brain',
  NO_THOUGHT_CENTER_FOR_MOVEMENT = 'Does not need a brain to move',
  VEGETATION                     = 'Made of swampstuff',

-- Types
  FANCIFUL                 = 'Fanciful',
  CASTE_MEGABEAST          = 'Megabeast',
  CASTE_SEMIMEGABEAST      = 'Semi-Megabeast',
  CASTE_BENIGN             = 'Benign',
  CASTE_POWER              = 'Power',
  CASTE_TITAN              = 'Titan',
  CASTE_FEATURE_BEAST      = 'Feature Beast',
  CASTE_UNIQUE_DEMON       = 'Unique Demon',
  CASTE_DEMON              = 'Demon',
  CASTE_NIGHT_CREATURE_ANY = 'Night Creature',
}

plantFlags = {
-- Seasonal
  SPRING = 'Grows during the spring',
  SUMMER = 'Grows during the summer',
  AUTUMN = 'Grows during the fall',
  WINTER = 'Grows during the winter',

-- Edible
  EDIBLE_VERMIN = 'Vermin',
  EDIBLE_RAW    = 'Raw',
  EDIBLE_COOKED = 'Cooked',

-- Items
  ITEMS_WEAPON        = 'Makes melee weapons',
  ITEMS_WEAPON_RANGED = 'Makes ranges weapons',
  ITEMS_ANVIL         = 'Makes anvils',
  ITEMS_AMMO          = 'Makes ammo',
  ITEMS_DIGGER        = 'Makes digging items',
  ITEMS_ARMOR         = 'Makes armor',
  ITEMS_DELICATE      = 'Makes delicate items',
  ITEMS_SIEGE_ENGINE  = 'Makes siege engine ammo',
  ITEMS_QUERN         = 'Makes querns',
  ITEMS_METAL         = 'Makes metal items',
  ITEMS_BARRED        = 'Makes barred items',
  ITEMS_SCALED        = 'Makes scaled items',
  ITEMS_LEATHER       = 'Makes leather items',
  ITEMS_SOFT          = 'Makes soft items',
  ITEMS_HARD          = 'Makes hard items',

-- Types
  IS_METAL = 'Metal',
  IS_GLASS = 'Glass',
  IS_STONE = 'Stone',

-- Materials
  SOFT             = 'Soft',
  HARD             = 'Hard',
  METAL            = 'Metal',
  BARRED           = 'Barred',
  SCALED           = 'Scaled',
  LEATHER          = 'Leather',
  METAL_MAT        = 'Metal',
  STONE_MAT        = 'Stone',
  WOOD_MAT         = 'Wood',
  GLASS_MAT        = 'Glass',
  CERAMIC_MAT      = 'Ceramic',
  SHELL_MAT        = 'Shell',
  BONE_MAT         = 'Bone',
  HARD_MAT         = 'Hard',
  SHEET_MAT        = 'Sheet',
  THREAD_PLANT_MAT = 'Plant Thread',
  SILK_MAT         = 'Silk',
  SOFT_MAT         = 'Soft',
  METAL_WEAPON_MAT = 'Metal',
  CAN_STONE        = 'Stone',

-- Uses
  TRAINING                = 'Training',
  FURNITURE               = 'Furniture',
  LIQUID_COOKING          = 'Cooking',
  LIQUID_SCOOP            = 'Liquid Scoop',
  GRIND_POWDER_RECEPTACLE = 'Powder Receptacle',
  GRIND_POWDER_GRINDER    = 'Powder Grinder',
  MEAT_CARVING            = 'Meat Carving',
  MEAT_BONING             = 'Meat Boning',
  MEAT_SLICING            = 'Meat Slicing',
  MEAT_CLEAVING           = 'Meat Cleaving',
  HOLD_MEAT_FOR_CARVING   = 'Meat Holding',
  MEAL_CONTAINER          = 'Meal Container',
  LIQUID_CONTAINER        = 'Liquid Container',
  FOOD_STORAGE            = 'Food Storage',
  HIVE                    = 'Artificial Hive',
  NEST_BOX                = 'Nest Box',
  SMALL_OBJECT_STORAGE    = 'Small Object Storage',
  TRACK_CART              = 'Track Cart',
  HEAVY_OBJECT_HAULING    = 'Heavy Object Hauling',
  STAND_AND_WORK_ABOVE    = 'Stand and Work Above',
  ROLL_UP_SHEET           = 'Roll Up Sheet',
  PROTECT_FOLDED_SHEETS   = 'Protect Paper',
  CONTAIN_WRITING         = 'Hold Writings',
  BOOKCASE                = 'Hold Books',
}
